mode: "test"
batch_size:
  train: 16
  eval: 1
  predict: 1
data_path:
  data_dir: "/mnt/data3/zz/cicc/"
  train: "data/train_data_Yi-1___5-34B-Chat-16K_analysis.json"
  eval: "data/val_data_Yi-1___5-34B-Chat-16K_analysis.json"
  test: "data/test_data_Yi-1___5-34B-Chat-16K_analysis.json"
model_path:
  pretrained_model_dir: "/mnt/data1/model/"
  pretrained_model: "ernie-3___0-xbase-zh"
  tokenizer: "ernie-3___0-xbase-zh"
  save: True
  snapshot_dir: "save_models"
  snapshot: "best_snapshot.pt"
criterion: "CrossEntropyLoss"
optimizer: "AdamW"
scheduler:
  name: "linear"
  ratio: 0.1
metrics: "ClassificationReport"
main_metric: "macro_avg_f1-score"
max_epochs: 10
seed: 42
early_stop: 10
lr: 0.000005
dropout: 0.6
CICC:
  max_length: 1024
  num_classes: 7
