mode: "train"
batch_size:
  train: 64
  eval: 2482
data_path:
  data_dir: "/mnt/data3/zz/cicc/"
  train: "data/train.txt"
  eval: "data/val.txt"
  test: "data/test.txt"
  vocab: "data/vocab.txt"
  predict: ""
model_path:
  pretrained_model_dir: "/mnt/data1/model/"
  tokenizer: "ernie-3___0-xbase-zh"
  save: True
  snapshot_dir: "save_models"
  snapshot: "best_snapshot.pt"
criterion: "CrossEntropyLoss"
optimizer: "AdamW"
scheduler:
  name: "linear"
  ratio: 0.1
metrics: "ClassificationReport"
main_metric: "macro_avg_f1-score"
max_epochs: 50
seed: 42
early_stop: 50
lr: 0.00005
dropout: 0.8
CICC:
  max_length: 512
  num_classes: 7
  embedding_dim: 256
  num_filters: 512
  vocab_size: 40000
  kernel_size: 4
  hidden_dim: 512

